### Get all todos
GET http://localhost:8000/api/users
X-API-Key: RAHASIA
Accept: application/json

### Create new todo
POST http://localhost:8000/api/users
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "fullname" : "nama orang",
  "email" : "orang1@email.com",
  "password" : "password",
  "forgot_password" : "password",
  "role_id" : 1
}

### Get todo by Id
GET http://localhost:8000/api/users/1
X-API-Key: RAHASIA
Accept: application/json

### Update todo by id
PUT http://localhost:8000/api/users/1
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "fullname" : "nama orang 1",
  "email" : "orang1@email.com",
  "password" : "password",
  "role_id" : 1
}

### Delete todo by id
DELETE http://localhost:8000/api/todos/2
X-API-Key: RAHASIA
Accept: application/json
